### ISSUE TITLE
No connection details shown in menu bar.

### ISSUE THREAD

**Issue by dsully** [aequitas/macos-menubar-wireguard#14]
Hi - thanks for the great project! It's so much nicer than using wg-quick from the CLI.

When I'm connected, there are no details of the connection in the menu bar:

<img width="113" alt="screenshot 2018-12-12 06 05 29" src="https://user-images.githubusercontent.com/22371/49874723-16ab0180-fdd4-11e8-8054-994f034a77ea.png">

I've checked permissions on both /etc/wireguard and /var/run/wireguard and those look ok.

Any thoughts?

**Comment by aequitas** [comment]
Hi, thanks for trying it out and the feedback.

The information missing is due to the user running the app not having read permission on the config files themselves (which is at least better than the previous behavior of crashing the app ;)). I'm currently in the process of moving config reading into the Helper so there will be no permission issues. I'll close this issue as soon as I release that version.

**Comment by aequitas** [comment]
I just uploaded a new version https://github.com/aequitas/macos-menubar-wireguard/releases/tag/1.12 could you try if it now works for you with regards to reading the configs?

**Comment by valantur** [comment]
hey @aequitas I'm trying out version 1.12 and I noticed I can't see the info either.
/usr/local/etc/wireguard/utun1.conf has the following permissions, according to chmod:
owner (my username): r+w
group (admin): none
others: none

I even tried giving setting 666 permissions so that everyone can read, write and execute, rebooted the app and re-established the connection to wireguard and still nothing, no info shown.

I hope this helps, let me know if you'd like me to try something else.

**Comment by eecharlie** [comment]
@dsully and @valantur I think that you specifically just need global read permission for /etc/wireguard so a directory listing can be obtained, *not* read permission for individual config files.

`sudo chmod o+r /etc/wireguard`

You probably shouldn't have user read permission for individual config files, because this exposes your PrivateKey, right? WireGuardStatusBarHelper will be able to read those because it runs as root.

**Comment by valantur** [comment]
just so you guys know, I applied very lax permissions 666 on both /usr/local/etc/wireguard (directory and files in it) and still no info on the active tunnel when I click the icon. I also tried clicking the icon while holding the option key down with the same results. I understand this is a minor issue and doesn't impact in any way the usability of the wireguard tunnel, so feel free to treat it as a super-low priority issue. Thanks for the wonderful app! I wish I knew how to code so I could help developing it!

**Comment by aequitas** [comment]
In that case it might be that the config files cannot be parsed. Would you mind sharing one of the configs (private key and endpoint ip can be censored) so I can test it locally. Or you could check the logs in `/Applications/Utilities/Console` to see if there might be an obvious error message.

**Comment by aequitas** [comment]
@valantur the latest version https://github.com/aequitas/macos-menubar-wireguard/releases/tag/1.13 should now also tell you it failed to read the configuration.

**Comment by valantur** [comment]
thank you @aequitas 
This version now shows and additional line that wasn't there before "Interface: utun1" but still no details on the connection. How is it that we are told if it failed to read the configuration? would a message pop up or do I have to check the logs?

Thanks!

Screenshot below:
<img width="237" alt="screen shot" src="https://user-images.githubusercontent.com/2516392/50612504-11028200-0e8f-11e9-83af-6159c3f9199a.png">

**Comment by valantur** [comment]
Here's my configuration file, the path is /usr/local/etc/wireguard/utun1.conf:

[INTERFACE]
Address = 192.168.79.2/24
PrivateKey = censored
ListenPort = censored
[PEER]
PublicKey = censored
Endpoint = censored
AllowedIPs = 192.168.0.0/16
PreSharedKey = censored

Sorry I had to censor almost everything out lol. Could it be that the app can't read/display the PreSharedKey entry? Some implementations of Wireguard don't use that.

**Comment by aequitas** [comment]
If there are errors they should show in the logs. But the screenshot makes your problem a lot clearer. The config is read but the correct values are not found so it defaults to empty values. I think it is due to the config sections being fully capatilized. Currently the config reading is case sensitive. If you rename them to Interface and Peer it should work. It intend to add case insensitive config parsing in the future.

**Comment by valantur** [comment]
> If there are errors they should show in the logs. But the screenshot makes your problem a lot clearer. The config is read but the correct values are not found so it defaults to empty values. I think it is due to the config sections being fully capatilized. Currently the config reading is case sensitive. If you rename them to Interface and Peer it should work. It intend to add case insensitive config parsing in the future.

Nailed it! It's working now. Thank you and keep up the good work!

**Comment by aequitas** [comment]
@dsully I'm gonna close this as I assume this issue is fixed for you as well. If not, feel free to reopen the issue.
