### ISSUE TITLE
Fix build settings

### ISSUE THREAD

**Issue by eecharlie** [aequitas/macos-menubar-wireguard#4]
`make clean` seems to delete image files that are tracked in the repo and appear to be actually needed; or, `make all` should invoke whatever process re-creates these files:

```
	deleted:    Wireguard Statusbar/Assets.xcassets/AppIcon.appiconset/logo-1024.png
	deleted:    Wireguard Statusbar/Assets.xcassets/AppIcon.appiconset/logo-128.png
	deleted:    Wireguard Statusbar/Assets.xcassets/AppIcon.appiconset/logo-16.png
	deleted:    Wireguard Statusbar/Assets.xcassets/AppIcon.appiconset/logo-256.png
	deleted:    Wireguard Statusbar/Assets.xcassets/AppIcon.appiconset/logo-32.png
	deleted:    Wireguard Statusbar/Assets.xcassets/AppIcon.appiconset/logo-512.png
	deleted:    Wireguard Statusbar/Assets.xcassets/AppIcon.appiconset/logo-64.png
```
(from `git status` following `git reset HEAD --hard` and `make clean`)

Edit: the build actually fails with
```
convert: unable to open image 'colorspace': No such file or directory @ error/blob.c/OpenBlob/3490.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/556.
convert: unable to open image 'gray': No such file or directory @ error/blob.c/OpenBlob/3490.
convert: unable to open image 'gray': No such file or directory @ error/blob.c/OpenBlob/3490.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/556.
make: *** [/var/folders/ph/m9w65qp51_34v7l0t338gjx40000gn/T//logo.png] Error 1
```

**Comment by aequitas** [comment]
`make clean` deleting the files should have already been solved by moving them to `mrproper` in https://github.com/aequitas/macos-menubar-wireguard/commit/8a4dda69207d424a12809028d809a571263b7df1#diff-b67911656ef5d18c4ae36cb6741b7965R96

As for the bug with generating new images, that is fixed in https://github.com/aequitas/macos-menubar-wireguard/commit/a622bfa879f2628631c221f8ac3bbbb0ef525fab

`make` (and `make all`) should remake all required targets. Including all images.

Let me know if there is any further issue.

**Comment by eecharlie** [comment]
My mistake, I hadn't sync'd my fork with your latest commits. I probably don't need a fork...
